- name: Install virt-manager
  apt:
    name: virt-manager
    state: latest

- name: Update libvirt images directory permissions
  acl:
    path: "/var/lib/libvirt/images"
    etype: user
    entity: "{{ ansible_user_id }}"
    permissions: rwx
    state: present

- name: Update libvirt images directory default permissions
  acl:
    path: "/var/lib/libvirt/images"
    etype: user
    entity: "{{ ansible_user_id }}"
    default: yes
    permissions: rwx
    state: present
