- name: Install virt-manager
  apt:
    name: virt-manager
    state: latest

- name: Update libvirt images directory permissions
  acl:
    path: "/var/lib/libvirt/images"
    etype: user
    entity: "{{ item }}"
    permissions: rwx
    state: present
  loop:
    - "{{ ansible_user_id }}"
    - "libvirt-qemu"
    - "libvirt-dnsmasq"

- name: Update libvirt images directory default permissions
  acl:
    path: "/var/lib/libvirt/images"
    etype: user
    entity: "{{ item }}"
    default: yes
    permissions: rwx
    state: present
  loop:
    - "{{ ansible_user_id }}"
    - "libvirt-qemu"
    - "libvirt-dnsmasq"
